[package]
name = "cbse-constants"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
lazy_static.workspace = true
num-bigint.workspace = true
