[package]
name = "cbse-console"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0"
hex = "0.4"
anyhow.workspace = true
z3.workspace = true
num-bigint.workspace = true
cbse-bitvec.workspace = true
cbse-exceptions.workspace = true
cbse-utils.workspace = true
