[package]
name = "cbse-hashes"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
sha3.workspace = true
keccak-hash.workspace = true
xxhash-rust.workspace = true
hex.workspace = true
